%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Holds the button / panel layout for the main window for the Amazing Race
%     prediction project
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
classdef AmazingGUI < handle
    properties
        fig
        
        %% Tabulation
        nav_tags
        dir_tag
        stat_tag
        
        %% Directory Tab
        h_bdir
        h_bcis
        h_tresults
        
        %% Stats Tab
        h_tfeatures
        h_baddteam
        h_bdropteam
        h_eteam
        h_bcalcstats
        h_bclear
        h_bsave
        h_bloadS19
        h_bloadS20
        h_bloadS21
        h_bloadS22
        h_bloadS23
        h_bloadS24
    end
    
    methods
        function obj = AmazingGUI()
            obj.fig = figure('Visible', 'on');
            
            %% Navigation Tabs
            obj.nav_tags = uitabgroup('Parent', obj.fig, ...
                'Units', 'normalized', ...
                'Position', [0, 0, 1, 0.95]);
            obj.dir_tag = uitab('Parent', obj.nav_tags, ...
                'Title', 'Files');
            obj.stat_tag = uitab('Parent', obj.nav_tags, ...
                'Title', 'Features');
            
            %% Files Tab
            obj.h_bdir = uicontrol('Style', 'pushbutton', ...
                'String', 'Choose Directory', ...
                'Units', 'normalized', ...
                'Position', [0.45, 0.95, 0.15, 0.05], ...
                'Parent', obj.dir_tag);
            
            obj.h_tresults = uitable('Tag', 'TestResultsTable',...
                'Units', 'normalized', ...
                'Position', [0, 0, 0.33, 1], 'ColumnEditable', ...
                [false], ...
                'ColumnName', {'Filename'}, ...
                'Parent', obj.dir_tag);
            
            obj.h_bcis = uicontrol('Style', 'pushbutton', ...
                'String', 'Cluster (CIS)', ...
                'Units', 'normalized', ...
                'Position', [0.45, 0.85, 0.225, 0.05], ...
                'Parent', obj.dir_tag);
            
            %% Stats Tab
            obj.h_tfeatures = uitable('Tag', 'FeatureTable',...
                'Units', 'normalized', ...
                'Position', [0, 0, 0.65, 1], ...
                    'Parent', obj.stat_tag);
                    %'ColumnEditable', ...
                %[false, true, true, true, true, true, true, true, true, ...
                %    true, true, true], ...
                %'ColumnName', {'Team Name', 'Total Screens', 'Avg Consec. Screens', ...
                %'Std Consec. Screens', 'Avg. To Next', ... 
                %'Sum delta next', 'Avg from Prev', 'Sum delt prev', ...
                %'Avg Position', 'Sum delt pos', 'Hi Pos', 'Lo Pos'}, ...
                
            
            obj.h_baddteam = uicontrol('Style', 'pushbutton', ...
                'Tag', 'AddTeamButton',...
                'String', 'Add Team', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.95, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            
            obj.h_bdropteam = uicontrol('Style', 'pushbutton', ...
                'Tag', 'DropTeamButton',...
                'String', 'Drop Team', ...
                'Units', 'normalized', ...
                'Position', [0.825, 0.95, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            
            obj.h_bclear = uicontrol('Style', 'pushbutton', ...
                'Tag', 'ClearTeamButton',...
                'String', 'Clear Teams', ...
                'Units', 'normalized', ...
                'Position', [0.825, 0.7, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            
            obj.h_eteam = uicontrol('Style', 'edit', ...
                'Tag', 'TeamText',...
                'Units', 'normalized', ...
                'Position', [0.65, 0.89, 0.3, 0.05], ...
                'Parent', obj.stat_tag);
            
            obj.h_bcalcstats = uicontrol('Style', 'pushbutton', ...
                'Tag', 'CalcStats',...
                'String', 'Calc Stats', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.7, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            
            obj.h_bsave = uicontrol('Style', 'pushbutton', ...
                'Tag', 'SaveData',...
                'String', 'Save', ...
                'Units', 'normalized', ...
                'Position', [0.8, 0.05, 0.15, 0.1], ...
                'Parent', obj.stat_tag);
            
            obj.h_bloadS19 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season19Teams',...
                'String', 'Load S19', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.5, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            obj.h_bloadS20 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season20Teams',...
                'String', 'Load S20', ...
                'Units', 'normalized', ...
                'Position', [0.825, 0.5, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            obj.h_bloadS21 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season21Teams',...
                'String', 'Load S21', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.425, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            obj.h_bloadS22 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season22Teams',...
                'String', 'Load S22', ...
                'Units', 'normalized', ...
                'Position', [0.825, 0.425, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            obj.h_bloadS23 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season23Teams',...
                'String', 'Load S23', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.35, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
            obj.h_bloadS24 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season24Teams',...
                'String', 'Load S24', ...
                'Units', 'normalized', ...
                'Position', [0.825, 0.35, 0.15, 0.05], ...
                'Parent', obj.stat_tag);
        end
    end
end