%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Holds the button / panel layout for the main window for the Amazing Race
%     prediction project
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
classdef AmazingGUI < handle
    properties
        fig
        
        %% Panels
        h_pfeedback
        h_ptabs
        
        %% Feedback Panels
        h_tdirnotice
        h_tteams
        
        %% Tabulation (I forget why they are named 'tag', maybe change?)
        nav_tags
        dir_tag
        team_tag
        cluster_tag
        stat_tag
        
        %% Directory Tab
        h_bdir
        h_tresults
        h_pimagepreview
        h_aimagepreview
        h_bnextimage
        h_bprevimage
        
        %% Team Tab
        h_baddteam
        h_bdropteam
        h_eteam
        h_bloadS19
        h_bloadS20
        h_bloadS21
        h_bloadS22
        h_bloadS23
        h_bloadS24
        
        %% Clustering Tab
        h_bcis
        h_ltargettop
        h_ltargetbot
        h_ltargetright
        h_ltargetleft
        h_etargettop
        h_etargetbot
        h_etargetright
        h_etargetleft
        
        h_llambda
        h_elambda
        h_lwthreshold
        h_ewthreshold
        h_lwmin
        h_ewmin
        
        h_pcpreview
        h_acpreview
        h_lstpreview
        
        %% Stats Tab
        h_tfeatures
        h_bcalcstats
        h_bclear
        h_bsave
    end
    
    methods
        function obj = AmazingGUI()
            obj.fig = figure('Visible', 'on');
            
            %% Feedback Header
            obj.h_pfeedback = uipanel('Title', 'Current Data', ...
                'FontSize', 12, ...
                'Units', 'normalized', ...
                'Position', [0, 0.65, 1, 0.35], ...
                'Parent', obj.fig);
            obj.h_tdirnotice = uicontrol(obj.h_pfeedback, ...
                'Style', 'text', ...
                'String' , 'Select a directory...', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.7, 0.9, 0.3]);
            obj.h_tteams = uicontrol(obj.h_pfeedback, ...
                'Style', 'text', 'String', 'Teams: None', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.05, 0.9, 0.6]);
            
            
            %% Workspace
            obj.h_ptabs = uipanel('Title', 'Workspace', ...
                'Position', [0, 0, 1, 0.65], ...
                'Parent', obj.fig);
            
            %% Navigation Tabs
            obj.nav_tags = uitabgroup('Parent', obj.h_ptabs, ...
                'Units', 'normalized', ...
                'Position', [0, 0, 1, 0.95]);
            obj.dir_tag = uitab('Parent', obj.nav_tags, ...
                'Title', 'Files');
            obj.team_tag = uitab('Parent', obj.nav_tags, ... 
                'Title', 'Teams');
            obj.cluster_tag = uitab('Parent', obj.nav_tags, ...
                'Title', 'Clustering');
            obj.stat_tag = uitab('Parent', obj.nav_tags, ...
                'Title', 'Features');
            
            %% Files Tab
            obj.h_bdir = uicontrol('Style', 'pushbutton', ...
                'String', 'Load Directory', ...
                'Units', 'normalized', ...
                'Position', [0.275, 0.9, 0.15, 0.1], ...
                'Parent', obj.dir_tag);
            
            obj.h_tresults = uitable('Tag', 'TestResultsTable',...
                'Units', 'normalized', ...
                'Position', [0, 0, 0.25, 1], 'ColumnEditable', ...
                [false], ...
                'ColumnName', {'Filename'}, ...
                'Parent', obj.dir_tag); %#ok<NBRAK>
            
            obj.h_pimagepreview = uipanel('Tag', 'DirPrev', ...
                'Units', 'normalized', ...
                'Position', [0.26, 0.2, 0.73, 0.65], ...
                'Parent', obj.dir_tag);
            
            obj.h_aimagepreview = axes('Units', 'normalized', ...
              'Position', [0 0 1 1], ...
              'Parent', obj.h_pimagepreview);
          
            obj.h_bprevimage = uicontrol('Style', 'pushbutton', ...
                'String', 'Prev', ...
                'Units', 'normalized', ...
                'Position', [0.4, 0.01, 0.2, 0.15], ...
                'Parent', obj.dir_tag);
            
            obj.h_bnextimage = uicontrol('Style', 'pushbutton', ...
                'String', 'Next', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.01, 0.2, 0.15], ...
                'Parent', obj.dir_tag);
            
            %% Teams Tab
            obj.h_baddteam = uicontrol('Style', 'pushbutton', ...
                'Tag', 'AddTeamButton',...
                'String', 'Add Team', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.90, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            
            obj.h_bdropteam = uicontrol('Style', 'pushbutton', ...
                'Tag', 'DropTeamButton',...
                'String', 'Drop Team', ...
                'Units', 'normalized', ...
                'Position', [0.825, 0.90, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            
            obj.h_bclear = uicontrol('Style', 'pushbutton', ...
                'Tag', 'ClearTeamButton',...
                'String', 'Clear Teams', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.05, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            
            obj.h_eteam = uicontrol('Style', 'edit', ...
                'Tag', 'TeamText',...
                'Units', 'normalized', ...
                'Position', [0.65, 0.79, 0.3, 0.1], ...
                'Parent', obj.team_tag);
            
            obj.h_bloadS19 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season19Teams',...
                'String', 'Load S19', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.85, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            obj.h_bloadS20 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season20Teams',...
                'String', 'Load S20', ...
                'Units', 'normalized', ...
                'Position', [0.225, 0.85, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            obj.h_bloadS21 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season21Teams',...
                'String', 'Load S21', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.7, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            obj.h_bloadS22 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season22Teams',...
                'String', 'Load S22', ...
                'Units', 'normalized', ...
                'Position', [0.225, 0.7, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            obj.h_bloadS23 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season23Teams',...
                'String', 'Load S23', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.55, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            obj.h_bloadS24 = uicontrol('Style', 'pushbutton', ...
                'Tag', 'Season24Teams',...
                'String', 'Load S24', ...
                'Units', 'normalized', ...
                'Position', [0.225, 0.55, 0.15, 0.1], ...
                'Parent', obj.team_tag);
            
            %% Clustering Tab
            obj.h_bcis = uicontrol('Style', 'pushbutton', ...
                'String', 'Cluster (CIS)', ...
                'Units', 'normalized', ...
                'Position', [0.84, 0.05, 0.15, 0.15], ...
                'Parent', obj.cluster_tag);
            obj.h_ltargettop = uicontrol('Style', 'text', ...
                'String', 'Top Limit', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.85, 0.2, 0.1]);
            obj.h_ltargetbot = uicontrol('Style', 'text', ...
                'String', 'Bottom Limit', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.74, 0.2, 0.1]);
            obj.h_ltargetleft = uicontrol('Style', 'text', ...
                'String', 'Left Limit', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.63, 0.2, 0.1]);
            obj.h_ltargetright = uicontrol('Style', 'text', ...
                'String', 'Right Limit', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.52, 0.2, 0.1]);
            
            obj.h_etargettop = uicontrol('Style', 'edit', ...
                'String', '570', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.85, 0.2, 0.1]);
            obj.h_etargetbot = uicontrol('Style', 'edit', ...
                'String', '600', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.74, 0.2, 0.1]);
            obj.h_etargetleft = uicontrol('Style', 'edit', ...
                'String', '250', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.63, 0.2, 0.1]);
            obj.h_etargetright = uicontrol('Style', 'edit', ...
                'String', '750', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.52, 0.2, 0.1]);
            
            obj.h_llambda = uicontrol('Style', 'text', ...
                'String', 'CIS Lambda', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.40, 0.2, 0.1]);
            obj.h_elambda = uicontrol('Style', 'edit', ...
                'String', '0.7', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.40, 0.2, 0.1]);
            
            obj.h_lwthreshold = uicontrol('Style', 'text', ...
                'String', 'White Threshold', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.29, 0.2, 0.1]);
            obj.h_ewthreshold = uicontrol('Style', 'edit', ...
                'String', '120', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.29, 0.2, 0.1]);
            
            obj.h_lwmin = uicontrol('Style', 'text', ...
                'String', 'Min White Pix.', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.05, 0.18, 0.2, 0.1]);
            obj.h_ewmin = uicontrol('Style', 'edit', ...
                'String', '1000', ...
                'Units', 'Normalized', 'Parent', obj.cluster_tag, ...
                'Position', [0.25, 0.18, 0.2, 0.1]);
            
            obj.h_pcpreview = uipanel('Tag', 'ClusterPreview', ...
                'Units', 'normalized', ...
                'Position', [0.5, 0.25, 0.45, 0.7], ...
                'Parent', obj.cluster_tag);
            obj.h_acpreview = axes('Units', 'normalized', ...
              'Position', [0 0 1 1], ...
              'Parent', obj.h_pcpreview); 
            
            %% Stats Tab
            obj.h_tfeatures = uitable('Tag', 'FeatureTable',...
                'Units', 'normalized', ...
                'Position', [0, 0, 0.65, 1], ...
                    'Parent', obj.stat_tag);
            
            obj.h_bcalcstats = uicontrol('Style', 'pushbutton', ...
                'Tag', 'CalcStats',...
                'String', 'Calc Stats', ...
                'Units', 'normalized', ...
                'Position', [0.65, 0.7, 0.15, 0.1], ...
                'Parent', obj.stat_tag);
            
            obj.h_bsave = uicontrol('Style', 'pushbutton', ...
                'Tag', 'SaveData',...
                'String', 'Save', ...
                'Units', 'normalized', ...
                'Position', [0.8, 0.05, 0.15, 0.1], ...
                'Parent', obj.stat_tag, ...
                'Visible', 'off');
        end
    end
end