%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MATLAB forces each function that is to be exported to have its own .m
% file. We may end up needing a lot of utility type functions. I do not
% want a lot of .m files running around. KLUDGE TIME : all utility
% functions are held in this class for general use in the model.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
classdef AmazingUtility
    enumeration
        SUCCESS, EMPTY_DIR
    end
    properties (Constant)
        Season19TeamList = {'Ernie & Cindy', 'Jeremy & Sandy', ...
                    'Amani & Marcus', 'Andy & Tommy', 'Bill & Cathi', ...
                    'Laurence & Zac', 'Justin & Jennifer', 'Liz & Marie', ...
                    'Kaylani & Lisa', 'Ethan & Jenna', 'Ron & Bill'};
        Season20TeamList = {'Rachel & Dave', 'Art & JJ', 'Brendon & Rachel', ...
                    'Vanessa & Ralph', 'Bopper & Mark', 'Nary & Jamie', ...
                    'Joey "Fitness" & Danny', 'Kerri & Stacy', ...
                    'Elliot & Andrew', 'Dave & Cherie', 'Misa & Maiya'};
        Season21TeamList = {'Josh & Brent', 'Jaymes & James', 'Trey & Lexi', ...
                    'Natalie & Nadiya', 'Abbie & Ryan', 'James & Abba', ...
                    'Rob & Kelley', 'Gary & Will', 'Caitlin & Brittany', ...
                    'Amy & Daniel', 'Rob & Sheila'};
        Season22TeamList = {'Bates & Anthony', 'Max & Katie', 'Mona & Beth', ...
                    'Caroline & Jennifer', 'Joey & Meghan', 'Chuck & Wynona', ...
                    'Pam & Winnie', 'Dave & Connor', 'Jessica & John', ...
                    'Idries & Jamil', 'Matt & Daniel'};
        Season23TeamList = {'Jason & Amy', 'Tim & Marie', 'Nicole & Travis', ...
                    'Leo & Jamal', 'Ally & Ashley', 'Nicky & Kim', ...
                    'Tim & Danny', 'Brandom & Adam', 'Chester & Ephraim', ...
                    'Rowan & Shane', 'Hostoke & Naina'};
        Season24TeamList = {'Dave & Conor', 'Caroline & Jennifer', 'Brendon & Rachel', ...
                    'Leo & Jamal', 'Jet & Cord', 'Flight Time & Big Easy', ...
                    'Jessica & John', 'Margie & Luke', 'Joey & Meghan', ...
                    'Mark & Mallory', 'Natalie & Nadiya'};
                
        SingleEpisodeGroups = {{'S19/E01'}, {'S20/E01'}, {'S21/E01'}, ...
            {'S22/E01'}, {'S23/E01'}, {'S24/E01'}};
        TwoEpisodeGroups = {
            {'S19/E01', 'S19/E02'}, ...
            {'S20/E01', 'S20/E02'}, ...
            {'S21/E01', 'S21/E02'}, ...
            {'S22/E01', 'S22/E02'}, ...
            {'S23/E01', 'S23/E02'}, ...
            {'S24/E01', 'S24/E02'}};
        ThreeEpisodeGroups = {
            {'S19/E01', 'S19/E02' ,'S19/E03'}, ...
            {'S20/E01', 'S20/E02', 'S20/E03'}, ...
            {'S21/E01', 'S21/E02', 'S21/E03'}, ...
            {'S22/E01', 'S22/E02', 'S22/E03'}, ...
            {'S23/E01', 'S23/E02', 'S23/E03'}, ...
            {'S24/E01', 'S24/E02', 'S24/E03'}};
        FourEpisodeGroups = {
            {'S19/E01', 'S19/E02' ,'S19/E03', 'S19/E04'}, ...
            {'S20/E01', 'S20/E02', 'S20/E03', 'S20/E04'}, ...
            {'S21/E01', 'S21/E02', 'S21/E03', 'S21/E04'}, ...
            {'S22/E01', 'S22/E02', 'S22/E03', 'S22/E04'}, ...
            {'S23/E01', 'S23/E02', 'S23/E03', 'S23/E04'}, ...
            {'S24/E01', 'S24/E02', 'S24/E03', 'S24/E04'}};
        FiveEpisodeGroups = {
            {'S19/E01', 'S19/E02' ,'S19/E03', 'S19/E04', 'S19/E05'}, ...
            {'S20/E01', 'S20/E02', 'S20/E03', 'S20/E04', 'S20/E05'}, ...
            {'S21/E01', 'S21/E02', 'S21/E03', 'S21/E04', 'S21/E05'}, ...
            {'S22/E01', 'S22/E02', 'S22/E03', 'S22/E04', 'S22/E05'}, ...
            {'S23/E01', 'S23/E02', 'S23/E03', 'S23/E04', 'S23/E05'}, ...
            {'S24/E01', 'S24/E02', 'S24/E03', 'S24/E04', 'S24/E05'}};
        
        
    end
    methods
       
    end
end